### ISSUE TITLE
Have links open in a new tab

### ISSUE THREAD

**Issue by PGORTY** [PTCResources/PTCResources.github.io#38]
How hard would it be to open links in a new tab on the website? For example, if I click on Course Material for Math 3 Honors, is it possible to open it up in a new tab instead of in the current one?

**Comment by jonathan-rogers-dev** [comment]
Which links should open in a new tab @PGORTY?

**Comment by PGORTY** [comment]
I was thinking that the Course Material and outside links should open in a new tab. Such as the released EOC's and unpacked documents.

**Comment by jonathan-rogers-dev** [comment]
Okay, should the videos made by the PTC open in a new tab @PGORTY ?

**Comment by PGORTY** [comment]
I don't think that will be necessary, but I think we should have some sort of a back button instead. (I already opened an issue on this).
