### ISSUE TITLE
Titles Based On Standards

### ISSUE THREAD

**Issue by PGORTY** [PTCResources/PTCResources.github.io#40]
Instead of the "Modules" on the website, kind of like how Math 2 and 3 are set up, can we have the titles based on the standards? For example, for Pre-Calc, we would have "Number and Quantity", "Algebra", and "Functions"; in each of those, we can have more sub-topics based on standard names, etc.?

**Comment by jonathan-rogers-dev** [comment]
I am going to hold off on the development of this feature until after the meeting on Tuesday.
