### ISSUE TITLE
Finding the Inverse of a Function needs to be added to NC Math III Honors

### ISSUE THREAD

**Issue by jonathan-rogers-dev** [PTCResources/PTCResources.github.io#61]
Information

Title: Finding the Inverse of a Function
Description: Finding and identifying the properties of a function's inverse from a table, graph, and function.
Author: Sanchit S.
Type: Video
Course: 
Video: https://drive.google.com/open?id=1tsvP9GVFN43TWvEc0hdL6RIWwo9bNiBV
Captions: 
Other:

**Comment by sanchit-shah** [comment]
Course: NC Math III Honors @jonathan-rogers-dev

**Comment by jonathan-rogers-dev** [comment]
Thanks @sanchit-shah!
